
language: java

env:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  MAVEN_CLI_OPTS: "'-s .m2/settings.xml -B'"
  MAVEN_DEPLOY_OPTS: "'-DaltReleaseDeploymentRepository=brain-iot-releases::default::https://nexus.repository-pert.ismb.it/repository/maven-releases -DaltSnapshotDeploymentRepository=brain-iot-snapshots::default::https://nexus.repository-pert.ismb.it/repository/maven-snapshots'"


# Cache downloaded dependencies and plugins between builds .
cache:
    directories:
     - .m2/repository

install:
  - mvn $MAVEN_CLI_OPTS validate

script:
  - mvn $MAVEN_CLI_OPTS verify

deploy:
  provider: script
  script: mvn $MAVEN_CLI_OPTS $MAVEN_DEPLOY_OPTS clean package org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy
  on:
    branch: master

#end
